# Generated by Django 5.1.6 on 2025-02-25 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_directmessagechannel_remove_message_message_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channel',
            name='unique_dm_channel_per_team_members',
        ),
        migrations.AddConstraint(
            model_name='directmessagechannel',
            constraint=models.CheckConstraint(condition=models.Q(('user1_id__lt', models.F('user2_id'))), name='user1_id_lt_user2_id'),
        ),
    ]
