# Generated by Django 5.1.6 on 2025-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_is_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='pinned_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
