# Generated by Django 5.1.7 on 2025-03-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
