# Generated by Django 5.1.7 on 2025-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_link_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
